
import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import { StartupProject } from '@/services/incubator.service';

export const downloadProjectAsZip = async (project: StartupProject) => {
    const zip = new JSZip();

    // Create a README
    const readmeContent = `# ${project.name}

${project.description}

## Generated via StartLabX AI Incubator
This project was autonomously generated by your AI Agent Squad.

### Contents:
${project.assets.map(a => `- ${a.title} (${a.type})`).join('\n')}
`;

    zip.file("README.md", readmeContent);

    // Add all assets
    project.assets.forEach(asset => {
        // Handle folder structure if title contains slashes, JSZip handles this automatically
        const filename = asset.title.startsWith('/') ? asset.title.slice(1) : asset.title;

        let content = asset.content;

        // If it's a JSON file and content is object, stringify it
        if (asset.format === 'json' && typeof content !== 'string') {
            content = JSON.stringify(content, null, 2);
        }

        zip.file(filename, content);
    });

    // Generate the zip file
    const content = await zip.generateAsync({ type: "blob" });
    saveAs(content, `${project.name.toLowerCase().replace(/\s+/g, '-')}-starter-kit.zip`);
};
